/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Yoga;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Gui_Kos extends javax.swing.JFrame {
    public Gui_Kos() {
        initComponents();
        DefaultTableModel dataModel= (DefaultTableModel) tabel.getModel();
        int rowCount = dataModel.getRowCount();
        while (rowCount > 0){
            dataModel.removeRow(rowCount - 1);
            rowCount = dataModel.getRowCount();
        }
    }
    public Connection conn;
    
    
    
    public void koneksi() throws SQLException {
        try {
            conn = null;
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/wisma_kost?user=root&password=");
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gui_Kos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException e) {
            Logger.getLogger(Gui_Kos.class.getName()).log(Level.SEVERE, null, e);
        } catch (Exception es) {
            Logger.getLogger(Gui_Kos.class.getName()).log(Level.SEVERE, null, es);
        }
    }
    
    public void clear (){
        txtNama.setText(" ");
        txtKasur.setText(" ");
        txtLemari.setText(" ");
        txtFasilitas.setText(" ");
        txtTgl.setText(" ");
        txtHarga.setText(" ");
        btnGroup.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCtk = new javax.swing.JButton();
        txtKasur = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnVIP = new javax.swing.JRadioButton();
        btnReg = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLemari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFasilitas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTgl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Tanggal Login");

        jLabel8.setText("Harga Kamar");

        btnCtk.setText("Simpan");
        btnCtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCtkActionPerformed(evt);
            }
        });

        txtKasur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKasurActionPerformed(evt);
            }
        });

        btnClose.setText("Kembali");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnVIP.setText("VIP");
        btnVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIPActionPerformed(evt);
            }
        });

        btnReg.setText("Regular");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("KOS WISMA PLATINUM");

        jLabel2.setText("Nama");

        txtLemari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLemariActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Kamar");

        txtFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFasilitasActionPerformed(evt);
            }
        });

        jLabel4.setText("Jenis Kasur");

        txtTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Lemari");

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        jLabel6.setText("Fasilitas");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Jenis Kamar", "Jenis Kasur", "Jenis Lemari", "Fasilitas", "Tanggal", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabel);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setText("Search 🔍");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtLemari, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKasur, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCtk)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKasur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLemari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCtk)
                    .addComponent(btnHapus)
                    .addComponent(btnClose))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCtkActionPerformed
       try {
        // Koneksi ke database
        koneksi();

        // Query SQL untuk mengecek apakah data dengan nama yang sama sudah ada
        String cekDuplikat = "SELECT COUNT(*) FROM Penghuni WHERE Nama = ?";
        try (PreparedStatement psCek = conn.prepareStatement(cekDuplikat)) {
            psCek.setString(1, txtNama.getText());
            ResultSet rs = psCek.executeQuery();
            rs.next();
            int count = rs.getInt(1);

            // Jika nama sudah ada, munculkan pesan dan keluar dari metode
            if (count > 0) {
                JOptionPane.showMessageDialog(null, "Data dengan nama yang sama sudah ada. Silakan masukkan nama lain.");
                return;
            }
        }

        // Query SQL untuk menyimpan data ke tabel Penghuni
        String sql = "INSERT INTO Penghuni (Nama, Jenis_Kamar, Jenis_Kasur, Jenis_Lemari, Fasilitas, Tanggal_Login, Harga_Kamar) VALUES (?, ?, ?, ?, ?, ?, ?)";

        // Membuat objek PreparedStatement untuk eksekusi query
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            // Mengisi parameter query dengan nilai dari inputan pengguna
            ps.setString(1, txtNama.getText());
            if (btnVIP.isSelected()) {
                ps.setString(2, "VIP");
            } else {
                ps.setString(2, "Regular");
            }
            ps.setString(3, txtKasur.getText());
            ps.setString(4, txtLemari.getText());
            ps.setString(5, txtFasilitas.getText());
            ps.setString(6, txtTgl.getText());
            ps.setDouble(7, Double.parseDouble(txtHarga.getText()));

            // Mengeksekusi query
            int result = ps.executeUpdate();

            // Menampilkan pesan berhasil atau gagal
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Data Anda Ditambahkan ke Tabel dan Database");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data ke Database");
            }
        }

        // Menutup koneksi
        conn.close();

        // Menampilkan data di tabel GUI setelah disimpan
        DefaultTableModel dataModel = (DefaultTableModel) tabel.getModel();
        List<Object> list = new ArrayList<>();
        list.add(txtNama.getText());
        if (btnVIP.isSelected()) {
            list.add("VIP");
        } else {
            list.add("Regular");
        }
        list.add(txtKasur.getText());
        list.add(txtLemari.getText());
        list.add(txtFasilitas.getText());
        list.add(txtTgl.getText());
        list.add(Double.parseDouble(txtHarga.getText()));
        dataModel.addRow(list.toArray());

    } catch (SQLException ex) {
        Logger.getLogger(Gui_Kos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnCtkActionPerformed

    private void txtKasurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKasurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKasurActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       Gui_MenuUtama mn = new Gui_MenuUtama();
        mn.setVisible(true);
        mn.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVIPActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegActionPerformed

    private void txtLemariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLemariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLemariActionPerformed

    private void txtFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFasilitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFasilitasActionPerformed

    private void txtTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
        // Koneksi ke database
        koneksi();

        // Mendapatkan indeks baris yang dipilih
        int selectedRow = tabel.getSelectedRow();

        // Jika tidak ada baris yang dipilih, munculkan pesan dan keluar dari metode
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus");
            return;
        }

        // Mendapatkan nilai nama dari baris yang dipilih
        String selectedNama = (String) tabel.getValueAt(selectedRow, 0);

        // Query SQL untuk menghapus data dari tabel Penghuni berdasarkan nama
        String sql = "DELETE FROM Penghuni WHERE Nama = ?";

        // Membuat objek PreparedStatement untuk eksekusi query
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            // Mengisi parameter query dengan nilai nama yang dipilih
            ps.setString(1, selectedNama);

            // Mengeksekusi query
            int result = ps.executeUpdate();

            // Menampilkan pesan berhasil atau gagal
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Data di Database berhasil dihapus");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal Menghapus Data di Database");
            }
        }

        // Menutup koneksi
        conn.close();

        // Menghapus baris yang dipilih dari tabel GUI
        DefaultTableModel dataModel = (DefaultTableModel) tabel.getModel();
        dataModel.removeRow(selectedRow);

    } catch (SQLException ex) {
        Logger.getLogger(Gui_Kos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
         try {
        // Koneksi ke database
        koneksi();

        // Query SQL untuk mencari data berdasarkan nama
        String sql = "SELECT * FROM Penghuni WHERE Nama LIKE ?";

        // Membuat objek PreparedStatement untuk eksekusi query
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            // Mengisi parameter query dengan nilai nama yang dicari
            ps.setString(1, "%" + txtCari.getText() + "%");

            // Mengeksekusi query
            ResultSet rs = ps.executeQuery();

            // Membersihkan data di tabel GUI
            DefaultTableModel dataModel = (DefaultTableModel) tabel.getModel();
            dataModel.setRowCount(0);

            // Menampilkan hasil pencarian di tabel GUI
            while (rs.next()) {
                Object[] rowData = {
                    rs.getString("Nama"),
                    rs.getString("Jenis_Kamar"),
                    rs.getString("Jenis_Kasur"),
                    rs.getString("Jenis_Lemari"),
                    rs.getString("Fasilitas"),
                    rs.getString("Tanggal_Login"),
                    rs.getDouble("Harga_Kamar")
                };
                dataModel.addRow(rowData);
            }

            // Jika tidak ada hasil pencarian, munculkan pesan
            if (dataModel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
            }
        }

        // Menutup koneksi
        conn.close();

    } catch (SQLException ex) {
        Logger.getLogger(Gui_Kos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Kos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Kos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Kos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Kos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Kos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCtk;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnHapus;
    private javax.swing.JRadioButton btnReg;
    private javax.swing.JRadioButton btnVIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtFasilitas;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKasur;
    private javax.swing.JTextField txtLemari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTgl;
    // End of variables declaration//GEN-END:variables
}
